version: '3.8'

services:
  backend:
    build: .
    image: guinnessoverflow/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
