version: '3.8'

services:
  backend:
    build: .
    image: guinnessoverflow/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - fitup-network
  
networks:
  fitup-network:
    name: fitup-network
    driver: bridge